//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_1_Technion
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_shift
    {
        public int ID { get; set; }
        public int employeeid { get; set; }
        public int shiftid { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual shift shift { get; set; }
    }
}
